import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Head from "next/head";
//Passo 1 - Configuração do projeto
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000/about"),
  title: "YanZinhoFlix",
  //Passo 3 - configurando pastas e components
  icons: {
    icon: "/favicon.svg",
  },
  description: "Generated by create next app",
  openGraph: {
    title: "YanZinhoFlix",
    description: "Tenha fácil acesso aos melhores contéudos",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
