import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000/about"),
  title: "YanZinhoFlix",
  icons: {
    icon: "/favicon.svg",
  },
  description: "Generated by create next app",
  openGraph: {
    title: "YanZinhoFlix",
    description: "Tenha fácil acesso aos melhores contéudos",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
      </body>

    </html>
  );
}
